// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.App = (function(_super) {
  __extends(App, _super);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  App.prototype.initialize = function() {
    var dealer, deck, player;
    this.set('deck', deck = new Deck());
    this.set('playerHand', deck.dealPlayer());
    this.set('dealerHand', deck.dealDealer());
    player = this.get('playerHand');
    dealer = this.get('dealerHand');
    player.on('bust', (function(_this) {
      return function() {
        return _this.trigger('lose');
      };
    })(this));
    player.on('win', (function(_this) {
      return function() {
        return _this.trigger('win');
      };
    })(this));
    player.on('stand', (function(_this) {
      return function() {
        dealer.at(0).flip();
        return dealer.play();
      };
    })(this));
    dealer.on('bust', (function(_this) {
      return function() {
        return _this.trigger('win');
      };
    })(this));
    return dealer.on('stand', (function(_this) {
      return function() {
        var dTotal, pTotal;
        pTotal = player.highest();
        dTotal = dealer.highest();
        if (dTotal > pTotal) {
          return _this.trigger('lose');
        } else if (pTotal > dTotal) {
          return _this.trigger('win');
        } else {
          return _this.trigger('push');
        }
      };
    })(this));
  };

  return App;

})(Backbone.Model);
