// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.App = (function(_super) {
  __extends(App, _super);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  App.prototype.initialize = function() {
    var deck, player;
    this.set('deck', deck = new Deck());
    this.set('playerHand', deck.dealPlayer());
    this.set('dealerHand', deck.dealDealer());
    player = this.get('playerHand');
    player.on('stand', function() {
      return this.trigeer('stand');
    });
    player.on('bust', (function(_this) {
      return function() {
        return _this.trigger('lose');
      };
    })(this));
    return player.on('win', (function(_this) {
      return function() {
        return _this.trigger('win');
      };
    })(this));
  };

  return App;

})(Backbone.Model);
